//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsDemo
    {
        public int ID { get; set; }
        public string StockCode { get; set; }
        public string Barkod { get; set; }
        public string SeoUrl { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeywords { get; set; }
        public string CategoryTitle { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Title { get; set; }
        public string TitleEng { get; set; }
        public Nullable<int> BoxQuantity { get; set; }
        public string MainImage { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string DescriptionEng { get; set; }
        public string DetailsEng { get; set; }
        public string Details { get; set; }
        public Nullable<int> Special { get; set; }
        public Nullable<int> ListNumber { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> MinOrder { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
        public Nullable<decimal> CargoPrice { get; set; }
        public Nullable<decimal> AffPercentage { get; set; }
        public Nullable<int> AffSeller { get; set; }
        public Nullable<int> WebService { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
